@apiKey = testebrabotoken
@apiUrl = https://protected-ridge-40630-cca6313c2003.herokuapp.com

### 1. Testar Ingestão de Repositório
# @name ingestTest
POST {{apiUrl}}/api/ingest
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "repositorio": "octocat/Spoon-Knife",
    "issues_limit": 10,
    "prs_limit": 10,
    "commits_limit": 10
}

### 2. Testar Consulta RAG (O TCC em ação!)
# @name queryTest
POST {{apiUrl}}/api/consultar
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "query": "Qual é o propósito deste repositório? Ele é um exemplo?",
    "repositorio": "octocat/Spoon-Knife"
}